### ISSUE TITLE
Documentation suggestions..

### ISSUE THREAD

**Issue by joshpurvis** [containership/containership#3]
Edit: separating the documentation suggestions from my actual issue.

Documentation suggestions:

- Mention in documentation that docker should have the remote RPC enabled in `/etc/defaults/docker` on followers.. (also on leaders? or no?)

        DOCKER_OPTS=" -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock"

- It seems node can't bind the ports unless sudo is used. It just silently fails to join the cluster. Maybe throw a warning/error?

- Which port ranges should be open in firewalls between followers/leaders? All unprivileged ports 1024-65535? I noticed via `netstat` that 27272 seems to be important for containership communication. This doesn't seem to be mentioned in docs.

**Comment by normanjoyner** [comment]
@joshpurvis thank you for the suggestions! We will be updating the documentation to include the answers to these questions.

**Comment by phildougherty** [comment]
@joshpurvis we had been running containership as root but I suppose we actually don't need to. However, we'll need to make some updates for it to work right.

If you run in development mode as non-root you'll likely see the following: 

NODE_ENV=development containership agent --mode follower --cidr x.x.x.x/24 -l debug
Error writing PID!

We'll need to update how/where/with what permissions we write the pid file, and likely log file. The user running containership will also need to be added to the docker unix group so that it has permissions to access the docker socket. I assume if you had added your user to the docker group you wouldn't have to set special DOCKER_OPTS to enable the tcp API endpoint. 

I believe node should be able to bind when run without root since it's using an unprivileged port.

27272 is the only port that you need open for containership itself to communicate. 

Once you run multi-tiered apps you'll need to have a larger range of ports open on the followers so that applications can communicate across followers.

We'll discuss the permissions issues with non-root operation and update the docs accordingly. Thanks!

**Comment by joshpurvis** [comment]
> I assume if you had added your user to the docker group you wouldn't have to set special DOCKER_OPTS to enable the tcp API endpoint.

Hm, I did add the ubuntu user to docker's group, but it's possible I didn't reboot the machines, which I think might be required for it to take effect. When I try again, I'll be sure to reboot.

Thanks for your help!

**Comment by normanjoyner** [comment]
Closing as we have new documentation at https://docs.containership.io
