### ISSUE TITLE
Why isn't plugin.cloud loaded and why can't I access Navigator?

### ISSUE THREAD

**Issue by dimitrovskif** [containership/containership#45]
I tried to set up my leader node by installing latest Node, Docker, build-essentials on Linux Mint 17, as well as containership (also installed all plugins: cloud cloud-hints navigator service-discovery). However, running any containership command logs an plugin.cloud error:

```
filip@filipmint ~ $ containership configure --api-url http://192.168.188.29:8080 
Failed to load containership.plugin.cloud plugin
api-url              http://192.168.188.29:8080                                                                          
api-version          v1                                                                                                  
plugin-location      /home/filip/.containership/plugins/node_modules
```

The error happens on any command. I can't visit Navigator either, even tried reloading it, reinstalling it, restarting docker daemon, reinstalling containership, and whatnot.

**Comment by normanjoyner** [comment]
@dimitrovskif if you wish to connect your cluster to ContainerShip Cloud, you must configure the Cloud plugin first. ContainerShip will still run without the Cloud plugin being configured, it will just throw that error.

To configure the plugin please see  https://docs.containership.io/docs/containership-cloud-setup. 
`$ containership plugin configure cloud --api_key <API_KEY> --organization <ORGANIZATION_NAME>`

This should resolve the errors you are seeing.

Regarding navigator, did you start containership in leader mode?
`sudo containership agent --mode leader`

**Comment by dimitrovskif** [comment]
So the `cloud` plugin is for the paid containership service? And the error is not important? 

Regarding navigator, it was started before you asked me, but I just ran it with `sudo` and it now works. Could that be the problem? If that is the case, there should be some warning that there are insufficient privileges.

**Comment by normanjoyner** [comment]
Yes, the `cloud` plugin will connect your cluster to the centralized ContainerShip Cloud service so you can manage it from there. It is currently in a free beta, but will eventually be a paid service. You can either uninstall the plugin if you do not wish to take advantage of this, or ignore the error as it will not affect your cluster.

Regarding permissions, that is most likely the case; however, the output is being logged to a file rather than stderr. If you run containership with NODE_ENV=development, the logs will be written to stdout and you should see something like:

```
→ NODE_ENV=development containership agent --mode leader
Error writing PID!
```

 I have created an [issue](https://github.com/containership/containership/issues/46) to address this.

**Comment by dimitrovskif** [comment]
Thanks for your support!
